linters-settings:
  funlen:
    lines: 100
    statements: 60
    govet:
      check-shadowing: true
    golint:
      min-confidence: 0
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - hugeParam
        - wrapperFunc
        - dupImport
        - whyNoLint
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - gocyclo
    - gofmt
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace